// -------------------------------------------------------------------
// Place your images in /public/images/ with these exact filenames.
// You supplied: logo.png, kitchen-1.jpg, feature-wall-1.jpg
// Additional high-quality Unsplash images are used as fallbacks.
// -------------------------------------------------------------------

export const COMPANY = {
  name:          "Smith Carpentry",
  tagline:       "Premium Carpentry & Joinery Across the UK",
  subtagline:
    "Expert craftsmanship delivering bespoke residential and commercial projects with precision, quality and attention to detail.",
  phone:      "07700 900000",
  email:      "info@smithcarpentry.co.uk",
  address:    "United Kingdom",
  whatsapp:   "447700900000",
  instagram:  "https://instagram.com/smithcarpentry",
  facebook:   "https://facebook.com/smithcarpentry",
  businessHours: [
    { day: "Monday – Friday", hours: "7:00am – 6:00pm" },
    { day: "Saturday",        hours: "8:00am – 4:00pm" },
    { day: "Sunday",          hours: "Emergency only"  },
  ],
};

export const STATS = [
  { value: 15,  suffix: "+", label: "Years Experience"   },
  { value: 500, suffix: "+", label: "Projects Completed" },
  { value: 450, suffix: "+", label: "Happy Clients"      },
  { value: 120, suffix: "+", label: "Commercial Projects" },
];

export const SERVICES = [
  {
    slug:        "shopfitting",
    title:       "Shopfitting",
    shortDesc:   "Complete commercial fit-outs for retail, offices, restaurants and hospitality venues.",
    description: "We deliver premium shopfitting solutions for commercial clients across the UK. From high-street retail to boutique restaurants, our team brings your vision to life with precision craftsmanship.",
    features:    ["Retail fit-outs", "Office interiors", "Restaurant & bar fit-outs", "Hospitality venues", "Complete refurbishments", "Bespoke fixtures & fittings"],
    image:       "/images/shopfit-2.jpg",
    gallery:     ["/images/shopfit-2.jpg",
                  "/images/shopfit-1.jpg",
                  "/images/shopfit-3.jpg",
                  "/images/feature-wall-1.jpg"],
    icon:        "🏪",
  },
  {
    slug:        "bespoke-carpentry",
    title:       "Bespoke Carpentry",
    shortDesc:   "Handcrafted media walls, alcove units, shelving and bespoke storage solutions.",
    description: "Our bespoke carpentry service transforms your living spaces with custom-made furniture and joinery. Every piece is designed and built to your exact specifications.",
    features:    ["Media walls", "Alcove units", "Floating shelving", "Bespoke cabinets", "Custom storage", "Feature walls"],
    image:       "/images/feature-wall-1.jpg",
    gallery:     ["/images/media-wall-3.jpg",
                  "/images/media-wall-2.jpg",
                  "/images/media-wall-1.jpg",
                  "/images/under-stairs-2.jpg",
                  "/images/under-stairs-1.jpg",
                  "/images/feature-wall-1.jpg"],
    icon:        "🪚",
  },
  {
    slug:        "garden-rooms",
    title:       "Garden Rooms",
    shortDesc:   "Fully insulated garden rooms, offices, gyms, studios and entertainment spaces.",
    description: "Our bespoke garden rooms are fully insulated, turnkey builds designed to extend your living or working space. From home offices to entertainment rooms — we handle everything.",
    features:    ["Fully insulated structures", "Home offices", "Garden gyms", "Art studios", "Entertainment rooms", "Turnkey builds"],
    image:       "/images/garden-kitchen-1.jpg",
    gallery:     ["/images/garden-kitchen-2.jpg",
                  "/images/garden-kitchen-3.jpg",
                  "/images/pergola-1.jpg",
                  "/images/garden-room-1.jpg",
                  "/images/garden-kitchen-1.jpg"],
    icon:        "🏡",
  },
  {
    slug:        "kitchens",
    title:       "Kitchens",
    shortDesc:   "Kitchen installations, bespoke designs, worktops, renovations and finishing.",
    description: "We design and install stunning kitchens that combine beauty with functionality. From bespoke shaker kitchens with marble islands to sleek handleless designs — every installation is delivered to the highest standard.",
    features:    ["Kitchen installation", "Bespoke shaker kitchens", "Handleless modern kitchens", "Quartz & marble worktops", "Island installation", "Appliance integration"],
    image:       "/images/kitchen-2.jpg",
    gallery:     ["/images/kitchen-2.jpg",
                  "/images/kitchen-5.jpg",
                  "/images/kitchen-3.jpg",
                  "/images/kitchen-4.jpg",
                  "/images/kitchen-8.jpg",
                  "/images/kitchen-1.jpg"],
    icon:        "🍳",
  },
  {
    slug:        "wardrobes",
    title:       "Wardrobes",
    shortDesc:   "Fitted, sliding, walk-in and bespoke wardrobe storage solutions.",
    description: "Our bespoke wardrobe solutions maximise every inch of your space. We design and build fitted, sliding, and walk-in wardrobes to the highest standard.",
    features:    ["Fitted wardrobes", "Sliding wardrobes", "Walk-in wardrobes", "Bespoke storage", "Dressing rooms", "Custom interiors"],
    image:       "/images/wardrobe-4.jpg",
    gallery:     ["/images/wardrobe-4.jpg",
                  "/images/bedroom-fitted-1.jpg",
                  "/images/bedroom-fitted-2.jpg",
                  "/images/loft-bedroom-2.jpg",
                  "/images/wardrobe-2.jpg",
                  "/images/wardrobe-1.jpg"],
    icon:        "🚪",
  },
  {
    slug:        "first-fix-carpentry",
    title:       "First Fix Carpentry",
    shortDesc:   "Timber framing, oak frame structures, stud walls, floor joists and structural carpentry.",
    description: "Our first fix carpentry service provides the structural backbone for any build. From traditional oak frame porches and entrance structures to modern stud partitions — we deliver solid, accurate work every time.",
    features:    ["Oak frame structures", "Timber framing", "Stud partition walls", "Floor joists & decking", "Structural beams", "Loft conversions"],
    image:       "/images/timber-frame-1.jpg",
    gallery:     ["/images/timber-frame-1.jpg",
                  "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80",
                  "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80"],
    icon:        "🔨",
  },
  {
    slug:        "second-fix-carpentry",
    title:       "Second Fix Carpentry",
    shortDesc:   "Doors, skirting, architraves, dado panelling, ironmongery and premium final finishes.",
    description: "The finish is everything. Our second fix carpentry service brings your project to completion with perfectly fitted doors, skirting, architraves, dado rail panelling and all the fine details that make the difference.",
    features:    ["Door hanging & fitting", "Skirting boards", "Architraves & casings", "Dado rail & wall panelling", "Ironmongery fitting", "Final finishing"],
    image:       "/images/staircase-1.jpg",
    gallery:     ["/images/second-fix-2.jpg",
                  "/images/internal-door-2.jpg",
                  "/images/internal-door-1.jpg",
                  "/images/second-fix-1.jpg",
                  "/images/staircase-9.jpg",
                  "/images/staircase-1.jpg"],
    icon:        "🪟",
  },
  {
    slug:        "staircases",
    title:       "Staircases",
    shortDesc:   "Staircase installation, refurbishments, dado panelling and oak frame structures.",
    description: "A statement staircase transforms any home. We design and install bespoke staircases — and bring them to life with second fix detailing including dado rail, wall panelling and quality ironmongery.",
    features:    ["New staircase installation", "Staircase refurbishments", "Dado rail & panelling", "Oak staircases", "Timber frame structures", "Handrail installation"],
    image:       "/images/staircase-4.jpg",
    gallery:     ["/images/staircase-7.jpg",
                  "/images/staircase-9.jpg",
                  "/images/staircase-8.jpg",
                  "/images/staircase-5.jpg",
                  "/images/staircase-4.jpg",
                  "/images/staircase-1.jpg"],
    icon:        "🪜",
  },
  {
    slug:        "pvc-windows-doors",
    title:       "PVC Windows & External Doors",
    shortDesc:   "Installation, replacement, composite doors, uPVC windows and energy efficient products.",
    description: "We supply and install the full range of PVC windows and external doors. Energy-efficient, secure and beautifully finished — installed to the highest standard every time.",
    features:    ["uPVC window installation", "Composite door fitting", "Window replacement", "French & bi-fold doors", "Energy-rated products", "Secure locking systems"],
    image:       "/images/external-door-2.jpg",
    gallery:     ["/images/external-door-2.jpg",
                  "/images/external-door-1.jpg",
                  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80"],
    icon:        "🏠",
  },
  {
    slug:        "plasterboarding",
    title:       "Plasterboarding & Drylining",
    shortDesc:   "Metal stud, MF ceilings, dot & dab, boarding and fire rated systems.",
    description: "Our drylining service provides fast, accurate plasterboarding for new builds, renovations and commercial projects. We work to tight tolerances to ensure perfect flat finishes every time.",
    features:    ["Metal stud partitions", "MF ceiling systems", "Dot & dab bonding", "Full board & plaster", "Fire-rated systems", "Acoustic partitions"],
    image:       "/images/commercial-3.jpg",
    gallery:     ["/images/commercial-3.jpg",
                  "/images/commercial-4.jpg",
                  "/images/commercial-2.jpg",
                  "/images/commercial-1.jpg"],
    icon:        "🧱",
  },
];

export const TESTIMONIALS = [
  {
    name:    "James Richardson",
    role:    "Homeowner, London",
    text:    "Smith Carpentry transformed our home. The bespoke media wall and alcove units are absolutely stunning — the finish is flawless and Harvey's attention to detail is second to none.",
    rating:  5,
    image:   "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    project: "Bespoke Media Wall",
  },
  {
    name:    "Sarah Thompson",
    role:    "Interior Designer, Manchester",
    text:    "I've worked with many carpenters over the years, but Smith Carpentry stands out. Reliable, professional, and the quality of their joinery is exceptional. My clients are always delighted.",
    rating:  5,
    image:   "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
    project: "Kitchen & Joinery",
  },
  {
    name:    "Marcus Williams",
    role:    "Restaurant Owner, Birmingham",
    text:    "Harvey fitted out our entire restaurant — the booth seating, bar fronts, and bespoke shelving all look incredible. Delivered on time and within budget. Can't recommend highly enough.",
    rating:  5,
    image:   "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    project: "Restaurant Shopfit",
  },
  {
    name:    "Emma Clarke",
    role:    "Property Developer, Leeds",
    text:    "We use Smith Carpentry across all our residential developments. First and second fix, staircases, kitchen installs — they do it all. Absolutely brilliant to work with.",
    rating:  5,
    image:   "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    project: "Full Residential Development",
  },
  {
    name:    "David Patel",
    role:    "Homeowner, Bristol",
    text:    "Our new garden room is absolutely perfect. Fully insulated, beautifully finished and exactly what we wanted. Harvey's team were professional throughout and the quality is outstanding.",
    rating:  5,
    image:   "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    project: "Garden Room",
  },
];

export const WHY_CHOOSE_US = [
  { icon: "🏆", title: "Award-Winning Quality",   description: "15+ years of delivering premium carpentry that exceeds client expectations on every project." },
  { icon: "🛡️", title: "Fully Insured",           description: "Full public liability and professional indemnity insurance for your complete peace of mind." },
  { icon: "📋", title: "Fixed Price Quotes",       description: "Transparent, detailed quotes with no hidden costs. What we quote is what you pay." },
  { icon: "⏰", title: "On Time, Every Time",      description: "We respect your time and schedule. Projects delivered on time without compromising quality." },
  { icon: "🤝", title: "Trusted by Hundreds",     description: "Over 450 satisfied clients across the UK — residential and commercial." },
  { icon: "✨", title: "Premium Finish",           description: "We obsess over the details. Every joint, every surface, every finish is to the highest standard." },
];

export const PORTFOLIO_ITEMS = [
  { id: "1",  title: "Modern Kitchen Installation",    category: "Kitchens",      image: "/images/kitchen-1.jpg",                                                              description: "Contemporary handleless kitchen with herringbone floor" },
  { id: "2",  title: "Commercial Feature Wall",        category: "Commercial",    image: "/images/feature-wall-1.jpg",                                                         description: "Slatted feature wall with integrated LED uplighting" },
  { id: "3",  title: "Restaurant Shopfit – Midlands",  category: "Commercial",    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",           description: "Complete restaurant interior fit-out" },
  { id: "4",  title: "Garden Home Office",             category: "Garden Rooms",  image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80",           description: "Fully insulated garden office with electric" },
  { id: "5",  title: "Fitted Wardrobe Suite",          category: "Wardrobes",     image: "https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=800&q=80",              description: "Floor-to-ceiling fitted wardrobe with soft-close doors" },
  { id: "6",  title: "Retail Shopfit – Manchester",    category: "Commercial",    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",           description: "Premium retail unit complete fit-out" },
  { id: "7",  title: "Oak Staircase Refurb",           category: "Residential",   image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",           description: "Complete oak staircase with glass balustrade" },
  { id: "8",  title: "Alcove Shelving Units",          category: "Joinery",       image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",           description: "Twin alcove units with integrated lighting" },
  { id: "9",  title: "Walk-In Wardrobe",               category: "Wardrobes",     image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80",           description: "Luxury dressing room with island unit" },
  { id: "10", title: "New Build Full Fit-Out",         category: "Residential",   image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",           description: "First & second fix throughout new-build property" },
  { id: "11", title: "Garden Entertainment Room",      category: "Garden Rooms",  image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80",           description: "Insulated garden bar & entertainment room" },
  { id: "12", title: "Bespoke Office Fit-Out",         category: "Commercial",    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80",  description: "Corporate office interior with bespoke joinery" },
  { id: "13", title: "Staircase & Dado Rail – Midlands", category: "Residential",  image: "/images/staircase-1.jpg",   description: "Full staircase refurb with dado rail panelling" },
  { id: "14", title: "Staircase Landing Second Fix",     category: "Residential",  image: "/images/staircase-2.jpg",   description: "Second fix panelling and dado rail on landing" },
  { id: "15", title: "Oak Handrail & Panelling",         category: "Residential",  image: "/images/staircase-3.jpg",   description: "Bespoke staircase panelling with oak handrail" },
  { id: "16", title: "Staircase Renovation",             category: "Residential",  image: "/images/staircase-4.jpg",   description: "Complete staircase renovation with second fix joinery" },
  { id: "17", title: "Oak Frame Entrance Porch",               category: "Commercial",  image: "/images/timber-frame-1.jpg", description: "Traditional oak frame porch with brick piers" },
  { id: "18", title: "Shaker Kitchen with Marble Island",      category: "Kitchens",    image: "/images/kitchen-2.jpg",      description: "Bespoke shaker kitchen, marble quartz island, herringbone floor" },
  { id: "19", title: "White Shaker Kitchen — Belfast Sink",    category: "Kitchens",    image: "/images/kitchen-3.jpg",      description: "Full shaker kitchen with integrated appliances & Belfast sink" },
  { id: "20", title: "Handleless White Gloss Kitchen",         category: "Kitchens",    image: "/images/kitchen-4.jpg",      description: "Contemporary handleless kitchen with Quooker tap & herringbone floor" },
  { id: "21", title: "Green Shaker Kitchen — Evening",           category: "Kitchens",     image: "/images/kitchen-5.jpg",       description: "Sage green shaker with oak uppers, marble island & pendant lighting" },
  { id: "22", title: "Green Shaker — Island Detail",            category: "Kitchens",     image: "/images/kitchen-6.jpg",       description: "Marble island worktop with pendant lighting & bar stools" },
  { id: "23", title: "Green Shaker — Worktop Close-Up",         category: "Kitchens",     image: "/images/kitchen-7.jpg",       description: "Quartz island worktop with filament pendant lights" },
  { id: "24", title: "Green Shaker — Oak Upper Cabinets",       category: "Kitchens",     image: "/images/kitchen-8.jpg",       description: "Oak shaker upper cabinets with black range cooker" },
  { id: "25", title: "Garden Kitchen — Outdoor Entertainment",  category: "Garden Rooms", image: "/images/garden-kitchen-1.jpg", description: "Bespoke outdoor kitchen with concrete-effect cabinets, built-in BBQ & LED lighting" },
  { id: "26", title: "Pine Staircase — Square Spindles",         category: "Residential",  image: "/images/staircase-5.jpg",     description: "New pine staircase with square-section spindles and newel posts" },
  { id: "27", title: "Pine Staircase — Night Angle",             category: "Residential",  image: "/images/staircase-6.jpg",     description: "Pine staircase with square spindles — side elevation showing full balustrade" },
  { id: "28", title: "Oak Winder Staircase — Glass Panels",      category: "Residential",  image: "/images/staircase-7.jpg",     description: "Solid oak winder staircase with glass balustrade panels, looking down from landing" },
  { id: "29", title: "Oak Winder Staircase — Treads Detail",     category: "Residential",  image: "/images/staircase-8.jpg",     description: "Oak winder treads with glass balustrade — view from bottom looking up" },
  { id: "30", title: "White Balustrade with Oak Handrail",       category: "Residential",  image: "/images/staircase-9.jpg",     description: "Painted white balustrade and spindles with contrasting solid oak handrail & newel cap" },
  { id: "31", title: "Minimalist White Floating TV Unit",        category: "Joinery",      image: "/images/media-wall-1.jpg",    description: "Full-width floating media unit with push-to-open doors and integrated soundbar recess" },
  { id: "32", title: "Navy Media Wall with Niche Lighting",      category: "Joinery",      image: "/images/media-wall-2.jpg",    description: "Navy blue media wall with illuminated display niches and wide-format electric fire" },
  { id: "33", title: "Stone-Effect Media Wall — Full Room",      category: "Joinery",      image: "/images/media-wall-3.jpg",    description: "White media wall with grey stone-effect niche backs, panoramic electric fire & open shelving" },
  { id: "34", title: "Stone-Effect Media Wall — Side Angle",     category: "Joinery",      image: "/images/media-wall-4.jpg",    description: "White media wall with stone niches and wide panoramic electric fire — alternative angle" },
  { id: "35", title: "Stone-Effect Media Wall — Room View",      category: "Joinery",      image: "/images/media-wall-5.jpg",    description: "Full living room view showing bespoke media wall with stone niches and electric fire" },
  { id: "36", title: "Bespoke Garden Storage Unit",             category: "Garden Rooms", image: "/images/garden-room-1.jpg",   description: "Bespoke flat-roof garden storage unit with grey cladding and roller shutter door" },
  { id: "37", title: "Arched External Door — Brick Surround",  category: "Residential",  image: "/images/external-door-1.jpg", description: "Bespoke painted arched external door with glazed panels set in a period brick archway" },
  { id: "38", title: "Gothic Arch Door — Rushall Field Farm",  category: "Residential",  image: "/images/external-door-2.jpg", description: "Bespoke painted gothic arch solid door with ring knocker set in a stone and brick archway" },
  { id: "39", title: "Timber Pergola Frame",                   category: "Garden Rooms", image: "/images/pergola-1.jpg",       description: "Large bespoke timber pergola with pressure-treated posts and rafters on concrete base" },
  { id: "40", title: "Under-Stairs Storage — Doors Closed",   category: "Joinery",      image: "/images/under-stairs-1.jpg",  description: "Bespoke under-stairs push-to-open storage unit with angled flush doors" },
  { id: "41", title: "Under-Stairs Storage — Interior",       category: "Joinery",      image: "/images/under-stairs-2.jpg",  description: "Under-stairs unit open showing internal shoe shelving, coat hooks and full-height storage" },
  { id: "42", title: "Garden Kitchen Bar — Night Shot",       category: "Garden Rooms", image: "/images/garden-kitchen-2.jpg", description: "Bespoke garden kitchen bar with grey cladding, roller shutter open, lit interior with built-in BBQ" },
  { id: "43", title: "Garden Kitchen Bar — Exterior",         category: "Garden Rooms", image: "/images/garden-kitchen-3.jpg", description: "Garden kitchen bar unit with grey cladding, black flat roof and black roller shutter closed" },
  { id: "44", title: "Landing Second Fix — Loft Hatch & Spotlights", category: "Residential", image: "/images/second-fix-1.jpg",  description: "Completed landing with fitted loft hatch, recessed spotlights and painted balustrade" },
  { id: "45", title: "Loft Conversion — Structural Work",    category: "Residential",  image: "/images/loft-1.jpg",           description: "First fix structural carpentry during loft conversion — boarding and insulation prep" },
  { id: "46", title: "Oak Internal Door — Angle 1",         category: "Residential",  image: "/images/internal-door-1.jpg",  description: "Solid oak internal door hung with white architrave and lever handle ironmongery" },
  { id: "47", title: "Oak Internal Door — Angle 2",         category: "Residential",  image: "/images/internal-door-2.jpg",  description: "Solid oak internal door — second angle showing grain detail and white painted casing" },
  { id: "48", title: "Full Landing — Oak Doors & Glass Balustrade", category: "Residential", image: "/images/second-fix-2.jpg", description: "Complete landing second fix with three oak doors, oak newel post, glass balustrade and skirting" },
  { id: "49", title: "Loft Room — Timber Slat Wall & Storage",  category: "Joinery",      image: "/images/loft-2.jpg",          description: "Loft conversion room with cedar slat feature wall and bespoke under-window storage drawers" },
  { id: "50", title: "Oak Barn Door on Black Sliding Track",    category: "Residential",  image: "/images/barn-door-1.jpg",     description: "Solid oak 4-panel barn door on black steel sliding track hardware" },
  { id: "51", title: "Under-Stairs Storage — Angled Doors",    category: "Joinery",      image: "/images/under-stairs-3.jpg",  description: "Under-stairs storage with bespoke angled flush MDF push-to-open doors viewed from hallway" },
  { id: "52", title: "Loft Bedroom Furniture — Close Angle",   category: "Wardrobes",    image: "/images/loft-bedroom-1.jpg",  description: "Bespoke loft bedroom fitted furniture — twin chest of drawers with dressing table centre unit" },
  { id: "53", title: "Loft Bedroom Furniture — Full Room",     category: "Wardrobes",    image: "/images/loft-bedroom-2.jpg",  description: "Full loft bedroom with bespoke fitted wardrobe, chest of drawers and dressing table" },
  { id: "54", title: "Commercial MF Ceiling & Drylining",     category: "Commercial",   image: "/images/commercial-1.jpg",    description: "Large commercial space with metal MF ceiling grid, plasterboard partitions and drylining in progress" },
  { id: "55", title: "Walnut Slat Feature Wall — Bar/Restaurant", category: "Commercial", image: "/images/shopfit-1.jpg",     description: "Premium dark walnut vertical slat feature wall with black ceiling and recessed spotlights" },
  { id: "56", title: "Ace Barbers — Shop Front Fit-Out",      category: "Commercial",   image: "/images/shopfit-2.jpg",       description: "Complete shop front fit-out for Ace Barbers — dark grey painted joinery, panelled door and fascia" },
  { id: "57", title: "Commercial Interior — Slatted Feature Wall", category: "Commercial", image: "/images/shopfit-3.jpg",   description: "Commercial interior fit-out with dark grey slatted wall panels, suspended ceiling grid and spotlights" },
  { id: "58", title: "Twin Alcove Units with Oak Mantel",       category: "Joinery",      image: "/images/alcove-1.jpg",    description: "Bespoke twin alcove units with floating shelves, shaker base cabinets and solid oak mantel beam" },
  { id: "59", title: "Full-Width Alcove Media Wall — Pre-Dec",  category: "Joinery",      image: "/images/alcove-2.jpg",    description: "Full-width alcove media wall with illuminated niche shelving and electric fire, pre-decoration stage" },
  { id: "60", title: "Staircase Wall Panelling — In Progress",  category: "Residential",  image: "/images/panelling-1.jpg", description: "Staircase wall panelling with pine handrail and panel moulding detail during installation" },
  { id: "61", title: "Sage Green Media Wall — In Progress",    category: "Joinery",      image: "/images/media-wall-6.jpg",  description: "Sage green media base unit with TV recess being built into drylining feature wall" },
  { id: "62", title: "Stone-Effect Feature Wall",              category: "Joinery",      image: "/images/feature-wall-2.jpg", description: "Full-height grey stone-effect feature wall with recessed spotlights" },
  { id: "63", title: "Retail Unit Drylining — First Fix",     category: "Commercial",   image: "/images/commercial-2.jpg",  description: "Commercial retail unit drylining — plasterboard wall with metal stud framing in progress" },
  { id: "64", title: "Large Commercial Drylining — Angle 1",  category: "Commercial",   image: "/images/commercial-3.jpg",  description: "Large commercial space drylining — plasterboard ceiling coffers and MF grid in progress" },
  { id: "65", title: "Large Commercial Drylining — Angle 2",  category: "Commercial",   image: "/images/commercial-4.jpg",  description: "Large commercial drylining — MF ceiling grid and plasterboard partitions, wide angle view" },
  { id: "66", title: "Bespoke Hallway Storage Unit",          category: "Joinery",      image: "/images/hallway-unit-1.jpg", description: "Bespoke painted hallway unit with tall shaker wardrobe, coat hooks, bench seat and overhead storage" },
  { id: "67", title: "Under-Stairs Storage — Interior Detail", category: "Joinery",     image: "/images/under-stairs-4.jpg", description: "Under-stairs storage unit open showing fitted shelving and pull-out drawers" },
  { id: "68", title: "Fitted Wardrobe Interior — Hanging & Drawers", category: "Wardrobes", image: "/images/wardrobe-1.jpg", description: "Fitted wardrobe interior with full-height hanging rail, shelving and integrated drawers" },
  { id: "69", title: "White Shaker Fitted Wardrobe — Interior", category: "Wardrobes",  image: "/images/wardrobe-2.jpg",   description: "White shaker fitted wardrobe open showing hanging rail, shelf and base drawer" },
  { id: "70", title: "Loft Bedroom Suite — Alternate Angle",   category: "Wardrobes",   image: "/images/loft-bedroom-3.jpg", description: "Loft bedroom bespoke fitted suite — full-height wardrobe, chest of drawers and dressing table" },
  { id: "71", title: "Grey Over-Bed Fitted Bedroom — Side",    category: "Wardrobes",   image: "/images/bedroom-fitted-1.jpg", description: "Bespoke grey fitted bedroom with over-bed storage, integrated bedside tables and lit headboard niche" },
  { id: "72", title: "Grey Over-Bed Fitted Bedroom — Front",   category: "Wardrobes",   image: "/images/bedroom-fitted-2.jpg", description: "Full-width grey fitted over-bed unit with flush doors, wall lights and integrated headboard" },
  { id: "73", title: "Mirror Sliding Wardrobe — In Progress",  category: "Wardrobes",   image: "/images/wardrobe-3.jpg",   description: "Full-height sliding mirror wardrobe being fitted, MDF surround and mirror door panels" },
  { id: "74", title: "Black Fitted Wardrobe & Desk Suite",     category: "Wardrobes",   image: "/images/wardrobe-4.jpg",   description: "Bespoke black matte fitted wardrobe with matching desk unit and chest of drawers" },
];

export const PORTFOLIO_CATEGORIES = ["All", "Commercial", "Residential", "Kitchens", "Joinery", "Garden Rooms", "Wardrobes"];

export const FAQS = [
  {
    question: "What areas do you cover?",
    answer:   "We cover the whole of the UK, with a primary focus on the Midlands, London, and the North of England. Travel costs may apply for projects outside a 50-mile radius.",
  },
  {
    question: "How do I get a quote?",
    answer:   "Simply contact us via the form, phone, or WhatsApp with your project details. We'll arrange a free site visit and provide a detailed, fixed-price quote within 48 hours.",
  },
  {
    question: "Are you fully insured?",
    answer:   "Yes — we carry full public liability insurance and professional indemnity insurance. Copies are available on request.",
  },
  {
    question: "How long does a typical project take?",
    answer:   "Timescales vary by project size. A bespoke fitted wardrobe typically takes 1–2 days, a kitchen 3–5 days, and larger commercial fit-outs are planned on a project-by-project basis.",
  },
  {
    question: "Do you provide a guarantee on your work?",
    answer:   "Absolutely. All our work comes with a 12-month workmanship guarantee. We stand behind everything we do.",
  },
  {
    question: "Can you work outside normal hours?",
    answer:   "We understand that some commercial projects need to be done outside trading hours. We're flexible and can accommodate early starts, late finishes, and weekend working.",
  },
];
