// -------------------------------------------------------------------
// Company data for Smith Carpentry — Nottinghamshire joinery specialists.
// Images live flat in /public/images/.
// -------------------------------------------------------------------

export const COMPANY = {
  name:          "Smith Carpentry",
  tagline:       "Quality Bespoke Carpentry Across Nottinghamshire",
  subtagline:
    "Trusted qualified carpenter with over 10 years of experience delivering bespoke joinery, kitchens, staircases, commercial fit-outs and high-quality carpentry across Nottinghamshire.",
  phone:      "07462 918476",
  email:      "smithcarpentryltd@outlook.com",
  address:    "Nottinghamshire, UK",
  whatsapp:   "447462918476",
  instagram:  "https://instagram.com/smith_carpentry_and_joinery",
  facebook:   "https://facebook.com/smithcarpentry",
  businessHours: [
    { day: "Monday – Friday", hours: "7:00am – 6:00pm" },
    { day: "Saturday",        hours: "8:00am – 4:00pm" },
    { day: "Sunday",          hours: "Emergency only"  },
  ],
};

export const STATS = [
  { value: 10,  suffix: "+", label: "Years Experience"   },
  { value: 500, suffix: "+", label: "Projects Completed" },
  { value: 450, suffix: "+", label: "Happy Clients"      },
  { value: 100, suffix: "%", label: "Satisfaction"       },
];

export const AREAS = [
  "Nottingham", "Mansfield", "Sutton-in-Ashfield", "Newark",
  "West Bridgford", "Arnold", "Worksop", "Chesterfield",
];

export const SERVICES = [
  {
    slug:        "shopfitting",
    title:       "Shopfitting",
    shortDesc:   "Complete commercial fit-outs for retail, offices, restaurants and hospitality venues across Nottinghamshire.",
    description: "We deliver premium shopfitting solutions for commercial clients across Nottinghamshire and the surrounding region. From high-street retail to boutique restaurants, our team brings your vision to life with precision craftsmanship.",
    features:    ["Retail fit-outs", "Office interiors", "Restaurant & bar fit-outs", "Hospitality venues", "Complete refurbishments", "Bespoke fixtures & fittings"],
    image:       "/images/media-wall-1.jpg",
    gallery:     ["/images/media-wall-1.jpg",
                  "/images/media-wall-5.jpg",
                  "/images/media-wall-10.jpg",
                  "/images/commercial-1.jpg",
                  "/images/commercial-3.jpg",
                  "/images/commercial-5.jpg"],
    icon:        "🏪",
  },
  {
    slug:        "bespoke-carpentry",
    title:       "Bespoke Carpentry",
    shortDesc:   "Handcrafted media walls, alcove units, shelving and bespoke storage solutions across Nottinghamshire.",
    description: "Our bespoke carpentry service transforms your living spaces with custom-made furniture and joinery. Every piece is designed and built to your exact specifications, right here in Nottinghamshire.",
    features:    ["Media walls", "Alcove units", "Floating shelving", "Bespoke cabinets", "Custom storage", "Feature walls"],
    image:       "/images/media-wall-41.jpg",
    gallery:     ["/images/media-wall-41.jpg",
                  "/images/media-wall-42.jpg",
                  "/images/media-wall-43.jpg",
                  "/images/bespoke-1.jpg",
                  "/images/bespoke-2.jpg",
                  "/images/bespoke-3.jpg"],
    icon:        "🪚",
  },
  {
    slug:        "garden-rooms",
    title:       "Garden Rooms",
    shortDesc:   "Fully insulated garden rooms, offices, gyms, studios and entertainment spaces across Nottinghamshire.",
    description: "Our bespoke garden rooms are fully insulated, turnkey builds designed to extend your living or working space. From home offices to entertainment rooms — we handle everything across Nottinghamshire.",
    features:    ["Fully insulated structures", "Home offices", "Garden gyms", "Art studios", "Entertainment rooms", "Turnkey builds"],
    image:       "/images/garden-kitchen-1.jpg",
    gallery:     ["/images/garden-kitchen-1.jpg",
                  "/images/garden-kitchen-2.jpg",
                  "/images/garden-room-52.jpg",
                  "/images/garden-room-53.jpg",
                  "/images/garden-room-15.jpg",
                  "/images/garden-room-18.jpg"],
    icon:        "🏡",
  },
  {
    slug:        "kitchens",
    title:       "Kitchens",
    shortDesc:   "Kitchen installations, bespoke designs, worktops, renovations and finishing across Nottinghamshire.",
    description: "We design and install stunning kitchens that combine beauty with functionality across Nottinghamshire. From bespoke shaker kitchens with marble islands to sleek handleless designs — every installation is delivered to the highest standard.",
    features:    ["Kitchen installation", "Bespoke shaker kitchens", "Handleless modern kitchens", "Quartz & marble worktops", "Island installation", "Appliance integration"],
    image:       "/images/kitchen-61.jpg",
    gallery:     ["/images/kitchen-61.jpg",
                  "/images/kitchen-62.jpg",
                  "/images/kitchen-63.jpg",
                  "/images/kitchen-64.jpg",
                  "/images/kitchen-65.jpg",
                  "/images/kitchen-66.jpg"],
    icon:        "🍳",
  },
  {
    slug:        "wardrobes",
    title:       "Wardrobes",
    shortDesc:   "Fitted, sliding, walk-in and bespoke wardrobe storage solutions across Nottinghamshire.",
    description: "Our bespoke wardrobe solutions maximise every inch of your space. We design and build fitted, sliding, and walk-in wardrobes to the highest standard throughout Nottinghamshire.",
    features:    ["Fitted wardrobes", "Sliding wardrobes", "Walk-in wardrobes", "Bespoke storage", "Dressing rooms", "Custom interiors"],
    image:       "/images/wardrobe-1.jpg",
    gallery:     ["/images/wardrobe-1.jpg",
                  "/images/wardrobe-2.jpg",
                  "/images/wardrobe-3.jpg",
                  "/images/wardrobe-4.jpg",
                  "/images/bespoke-desk-1.jpg",
                  "/images/under-stairs-1.jpg"],
    icon:        "🚪",
  },
  {
    slug:        "first-fix-carpentry",
    title:       "First Fix Carpentry",
    shortDesc:   "Timber framing, oak frame structures, stud walls, floor joists and structural carpentry across Nottinghamshire.",
    description: "Our first fix carpentry service provides the structural backbone for any build across Nottinghamshire. From traditional oak frame porches and entrance structures to modern stud partitions — we deliver solid, accurate work every time.",
    features:    ["Oak frame structures", "Timber framing", "Stud partition walls", "Floor joists & decking", "Structural beams", "Loft conversions"],
    image:       "/images/garden-room-3.jpg",
    gallery:     ["/images/garden-room-3.jpg",
                  "/images/garden-room-4.jpg",
                  "/images/garden-room-1.jpg",
                  "/images/garden-room-2.jpg",
                  "/images/commercial-10.jpg",
                  "/images/commercial-15.jpg"],
    icon:        "🔨",
  },
  {
    slug:        "second-fix-carpentry",
    title:       "Second Fix Carpentry",
    shortDesc:   "Doors, skirting, architraves, dado panelling, ironmongery and premium final finishes across Nottinghamshire.",
    description: "The finish is everything. Our second fix carpentry service brings your project to completion with perfectly fitted doors, skirting, architraves, dado rail panelling and all the fine details that make the difference — across Nottinghamshire.",
    features:    ["Door hanging & fitting", "Skirting boards", "Architraves & casings", "Dado rail & wall panelling", "Ironmongery fitting", "Final finishing"],
    image:       "/images/staircase-3.jpg",
    gallery:     ["/images/staircase-3.jpg",
                  "/images/staircase-6.jpg",
                  "/images/staircase-9.jpg",
                  "/images/staircase-12.jpg",
                  "/images/staircase-15.jpg",
                  "/images/staircase-1.jpg"],
    icon:        "🪟",
  },
  {
    slug:        "staircases",
    title:       "Staircases",
    shortDesc:   "Staircase installation, refurbishments, dado panelling and oak frame structures across Nottinghamshire.",
    description: "A statement staircase transforms any home. We design and install bespoke staircases across Nottinghamshire — and bring them to life with second fix detailing including dado rail, wall panelling and quality ironmongery.",
    features:    ["New staircase installation", "Staircase refurbishments", "Dado rail & panelling", "Oak staircases", "Timber frame structures", "Handrail installation"],
    image:       "/images/staircase-1.jpg",
    gallery:     ["/images/staircase-1.jpg",
                  "/images/staircase-2.jpg",
                  "/images/staircase-4.jpg",
                  "/images/staircase-5.jpg",
                  "/images/staircase-7.jpg",
                  "/images/staircase-10.jpg"],
    icon:        "🪜",
  },
  {
    slug:        "pvc-windows-doors",
    title:       "PVC Windows & External Doors",
    shortDesc:   "Installation, replacement, composite doors, uPVC windows and energy efficient products across Nottinghamshire.",
    description: "We supply and install the full range of PVC windows and external doors across Nottinghamshire. Energy-efficient, secure and beautifully finished — installed to the highest standard every time.",
    features:    ["uPVC window installation", "Composite door fitting", "Window replacement", "French & bi-fold doors", "Energy-rated products", "Secure locking systems"],
    image:       "/images/garden-room-11.jpg",
    gallery:     ["/images/garden-room-11.jpg",
                  "/images/garden-room-12.jpg",
                  "/images/garden-room-13.jpg",
                  "/images/garden-room-19.jpg"],
    icon:        "🏠",
  },
  {
    slug:        "plasterboarding",
    title:       "Plasterboarding & Drylining",
    shortDesc:   "Metal stud, MF ceilings, dot & dab, boarding and fire rated systems across Nottinghamshire.",
    description: "Our drylining service provides fast, accurate plasterboarding for new builds, renovations and commercial projects across Nottinghamshire. We work to tight tolerances to ensure perfect flat finishes every time.",
    features:    ["Metal stud partitions", "MF ceiling systems", "Dot & dab bonding", "Full board & plaster", "Fire-rated systems", "Acoustic partitions"],
    image:       "/images/commercial-3.jpg",
    gallery:     ["/images/commercial-3.jpg",
                  "/images/commercial-6.jpg",
                  "/images/commercial-9.jpg",
                  "/images/commercial-12.jpg",
                  "/images/commercial-1.jpg",
                  "/images/commercial-2.jpg"],
    icon:        "🧱",
  },
];

export const TESTIMONIALS = [
  {
    name:    "James Richardson",
    role:    "Homeowner, Nottingham",
    text:    "Smith Carpentry transformed our home. The bespoke media wall and alcove units are absolutely stunning — the finish is flawless and Harvey's attention to detail is second to none.",
    rating:  5,
    project: "Bespoke Media Wall",
  },
  {
    name:    "Sarah Thompson",
    role:    "Interior Designer, West Bridgford",
    text:    "I've worked with many carpenters over the years, but Smith Carpentry stands out. Reliable, professional, and the quality of their joinery is exceptional. My clients are always delighted.",
    rating:  5,
    project: "Kitchen & Joinery",
  },
  {
    name:    "Marcus Williams",
    role:    "Restaurant Owner, Mansfield",
    text:    "Harvey fitted out our entire restaurant — the booth seating, bar fronts, and bespoke shelving all look incredible. Delivered on time and within budget. Can't recommend highly enough.",
    rating:  5,
    project: "Restaurant Shopfit",
  },
  {
    name:    "Emma Clarke",
    role:    "Property Developer, Newark",
    text:    "We use Smith Carpentry across all our residential developments. First and second fix, staircases, kitchen installs — they do it all. Absolutely brilliant to work with.",
    rating:  5,
    project: "Full Residential Development",
  },
  {
    name:    "David Patel",
    role:    "Homeowner, Arnold",
    text:    "Our new garden room is absolutely perfect. Fully insulated, beautifully finished and exactly what we wanted. Harvey's team were professional throughout and the quality is outstanding.",
    rating:  5,
    project: "Garden Room",
  },
];

export const WHY_CHOOSE_US = [
  { icon: "🏆", title: "Qualified & Trusted",     description: "A trusted, qualified carpenter with 10+ years of delivering premium carpentry across Nottinghamshire." },
  { icon: "🛡️", title: "Fully Insured",           description: "Full public liability and professional indemnity insurance for your complete peace of mind." },
  { icon: "📋", title: "Free Fixed Quotes",       description: "Transparent, detailed quotes with no hidden costs. What we quote is what you pay." },
  { icon: "⏰", title: "On Time, Every Time",      description: "We respect your time and schedule. Projects delivered on time without compromising quality." },
  { icon: "🤝", title: "Domestic & Commercial",   description: "Over 450 satisfied clients across Nottinghamshire — homeowners and commercial clients alike." },
  { icon: "✨", title: "Attention to Detail",      description: "We obsess over the details. Every joint, every surface, every finish is to the highest standard." },
];

export const FAQS = [
  {
    question: "What areas do you cover?",
    answer:   "We are based in Nottinghamshire and cover Nottingham, Mansfield, Sutton-in-Ashfield, Newark, West Bridgford, Arnold, Worksop, Chesterfield and all surrounding areas.",
  },
  {
    question: "How do I get a quote?",
    answer:   "Simply contact us via the form, phone, or WhatsApp with your project details. We'll arrange a free site visit and provide a detailed, fixed-price quote within 48 hours.",
  },
  {
    question: "Are you fully insured?",
    answer:   "Yes — we carry full public liability insurance and professional indemnity insurance. Copies are available on request.",
  },
  {
    question: "How long does a typical project take?",
    answer:   "Timescales vary by project size. A bespoke fitted wardrobe typically takes 1–2 days, a kitchen 3–5 days, and larger commercial fit-outs are planned on a project-by-project basis.",
  },
  {
    question: "Do you provide a guarantee on your work?",
    answer:   "Absolutely. All our work comes with a 12-month workmanship guarantee. We stand behind everything we do.",
  },
  {
    question: "Can you work outside normal hours?",
    answer:   "We understand that some commercial projects need to be done outside trading hours. We're flexible and can accommodate early starts, late finishes, and weekend working.",
  },
];
